groups:
    - name: Vera
      members: 
        - id: Balkon
          host: http://192.168.178.103:4000
        - id: Fenster
          host: http://192.168.178.102:4000

      plugs:
        - id: Nachtlampe
          host: "192.168.178.30"
        - id: Telefon
          host: "192.168.178.28"
    

        
      

    