groups:
    - name: Vera
      members: 
        - id: test-device
          host: http://192.168.178.103:4000
        - id: dev-macbook
          host: http://192.168.178.96:4000
    

        
      

    